#!/usr/bin/env bash
set -euo pipefail

echo "================================================"
echo "  MUDA Fairness Verification - Rocq Build Script"
echo "================================================"
echo ""

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# Tools
command -v rocq >/dev/null 2>&1 || error "rocq not found. Install Rocq v9.1.0+ and add to PATH."
ROCQ_VER="$(rocq c --print-version 2>/dev/null || rocq --version 2>/dev/null || echo 'version unknown')"
info "Using Rocq: ${ROCQ_VER}"
echo ""

# Step 1: Clean old build artifacts
info "Cleaning old build artifacts..."
find . \( -name "*.vo" -o -name "*.vok" -o -name "*.vos" \
          -o -name "*.glob" -o -name "*.aux" -o -name ".*.aux" \
          -o -name ".lia.cache" \) -type f -delete 2>/dev/null || true
rm -f .depend Makefile.rocq 2>/dev/null || true   # rocq equivalents
info "Clean complete."
echo ""

# Step 2: Verify directory structure
info "Verifying directory structure..."
if [[ ! -d "LTL" ]] || [[ ! -d "MUDA" ]] || [[ ! -d "Fairness" ]]; then
    error "Missing required directories. Expected: LTL/, MUDA/, Fairness/"
fi

# Count .v files (unchanged)
LTL_COUNT=$(find LTL -name "*.v" 2>/dev/null | wc -l | tr -d ' ')
MUDA_COUNT=$(find MUDA -name "*.v" 2>/dev/null | wc -l | tr -d ' ')
FAIRNESS_COUNT=$(find Fairness -name "*.v" 2>/dev/null | wc -l | tr -d ' ')

info "Found $LTL_COUNT LTL files, $MUDA_COUNT MUDA files, $FAIRNESS_COUNT Fairness files"
echo ""

# Step 3: Generate _CoqProject  (KEPT, unchanged as requested)
info "Generating _CoqProject..."
cat > _CoqProject <<'EOF'
# Coq Project Configuration for MUDA Fairness Verification
# Generated by build.sh

# Logical roots
-R LTL LTL
-R MUDA MUDA
-R Fairness Fairness


# Suppress common warnings
-arg -w -arg -notation-overridden
-arg -w -arg -redundant-canonical-projection

# ===== LTL Foundation (Layer 1) =====
LTL/Syntax.v
LTL/Semantics.v
LTL/Axioms.v
LTL/Soundness.v
LTL/Completeness.v
LTL/LTL.v

# ===== MUDA Protocol (Layer 2) =====
MUDA/Eqb.v
MUDA/Types.v
MUDA/State.v
MUDA/Sorting.v
MUDA/Matching.v
MUDA/ClearingPrice.v
MUDA/Transitions.v
MUDA/Atoms.v
MUDA/MUDA.v

# ===== Fairness Verification (Layer 3) =====
Fairness/Interpretation.v
Fairness/PriorityFairness.v
Fairness/QuantityFairness.v
Fairness/ClearingPriceFairness.v
Fairness/MatchFinality.v
Fairness/Maximality.v
Fairness/RejectionFairness.v
Fairness/All.v

# ===== Simulation (Layer 4) =====
Example/CloudMarket.v

EOF
info "_CoqProject generated."
echo ""

# Step 4: Check if files in _CoqProject exist (KEPT)
info "Verifying all files exist..."
MISSING=0
while IFS= read -r line; do
    # Skip comments and flags
    [[ "$line" =~ ^# ]] && continue
    [[ "$line" =~ ^-.*$ ]] && continue
    [[ -z "$line" ]] && continue
    if [[ ! -f "$line" ]]; then
        warn "Missing file: $line"
        MISSING=$((MISSING + 1))
    fi
done < _CoqProject

if [[ $MISSING -gt 0 ]]; then
    error "Found $MISSING missing files. Please create them before building."
fi
info "All files verified."
echo ""

# ---- Rocq replacement for Steps 5–7 ----

# Step 5 (Rocq): Compute dependencies into .depend
info "Computing dependencies with rocq dep..."
rocq dep -f _CoqProject > .depend
info "Dependency file '.depend' generated."
echo ""

# Step 6: Determine number of parallel jobs (KEPT)
NPROC=2
if command -v nproc &> /dev/null; then
    NPROC=$(nproc)
elif command -v sysctl &> /dev/null; then
    NPROC=$(sysctl -n hw.ncpu 2>/dev/null || echo 2)
elif command -v getconf &> /dev/null; then
    NPROC=$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)
fi
info "Building with $NPROC parallel jobs..."
echo ""

# Step 7 (Rocq): Build using a tiny Makefile that respects _CoqProject selection
ENABLED_VFILES=$(grep -E '^[[:space:]]*[^#-].*\.v[[:space:]]*$' _CoqProject | tr -d '\r' | xargs || true)
[[ -n "${ENABLED_VFILES}" ]] || error "No .v files enabled in _CoqProject. Uncomment entries to build."

VO_TARGETS=()
for v in ${ENABLED_VFILES}; do VO_TARGETS+=("${v%.v}.vo"); done

# Extract -R roots from _CoqProject and flatten into one line
ROOT_FLAGS=$(grep -E '^[[:space:]]*-R[[:space:]]+' _CoqProject \
  | awk '{print "-R",$2,$3}' | tr -d '\r' | xargs)
[[ -n "${ROOT_FLAGS}" ]] || error "No -R roots found in _CoqProject."

info "Preparing Makefile.rocq..."
{
  printf '%s\n' '# Auto-generated minimal Rocq makefile (portable)'
  printf '%s\n' 'PROJECT := _CoqProject'
  printf 'VFILES := %s\n' "${ENABLED_VFILES}"
  printf '%s\n' 'VOFILES := $(VFILES:.v=.vo)'
  printf 'ROOT_FLAGS := %s\n' "${ROOT_FLAGS}"
  printf '%s\n' ''
  printf '%s\n' 'all: .depend $(VOFILES)'
  printf '%s\n' ''
  printf '%s\n' '.depend: $(PROJECT)'
  # pass ROOT_FLAGS here too (harmless with -f, helpful if you ever omit -f)
  printf '%s%s\n' $'\t' 'rocq dep $(ROOT_FLAGS) -f $(PROJECT) > .depend'
  printf '%s\n' ''
  printf '%s\n' '-include .depend'
  printf '%s\n' ''
  printf '%s\n' '%.vo: %.v'
  # <<< pass ROOT_FLAGS so imports like From LTL Require Import Syntax resolve
  printf '%s%s\n' $'\t' 'rocq compile $(ROOT_FLAGS) $<'
  printf '%s\n' ''
  printf '%s\n' 'clean:'
  printf '%s%s\n' $'\t' 'find . \( -name "*.vo" -o -name "*.vok" -o -name "*.vos" -o -name "*.glob" -o -name "*.aux" -o -name ".*.aux" -o -name ".lia.cache" \) -type f -delete'
  printf '%s%s\n' $'\t' 'rm -f .depend'
  printf '%s\n' ''
  printf '%s\n' '.PHONY: all clean'
} > Makefile.rocq

# Build only the selected targets (do NOT rebuild everything)
START_TIME=$(date +%s)
if make -f Makefile.rocq -j"$NPROC" "${VO_TARGETS[@]}"; then
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    echo ""
    info "✓ Build successful in ${DURATION}s"
else
    echo ""
    error "Build failed. Check errors above."
fi

# Step 8: Check for admitted lemmas (KEPT)
echo ""
info "Checking for admitted lemmas..."
# With 'set -euo pipefail', bare grep with no matches returns 1 and would exit the script.
# Wrap grep with '|| true' to make the pipeline succeed when there are zero matches.
ADMITS="$( (grep -r "Admitted\." LTL/ MUDA/ Fairness/ 2>/dev/null || true) | wc -l | tr -d ' ' )"
if [[ ${ADMITS:-0} -eq 0 ]]; then
    info "✓ No admitted lemmas found. All proofs complete!"
else
    warn "Found $ADMITS admitted lemma(s):"
    grep -rn "Admitted\." LTL/ MUDA/ Fairness/ 2>/dev/null || true
fi

echo ""
echo "================================================"
echo "  Build Complete"
echo "================================================"
echo ""
info "Next steps:"
info "  - Comment or uncomment .v entries in _CoqProject to control what builds"
info "  - Use 'rocq doc -html -d html ${ENABLED_VFILES}' for HTML docs"
echo ""

# Optional: post-build cleanup hook
./clean.sh || true
