#!/usr/bin/env bash
set -euo pipefail

echo "================================================"
echo "  MUDA Fairness Verification - Build Script"
echo "================================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored messages
info() { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# Step 1: Clean old build artifacts
info "Cleaning old build artifacts..."
find . \( -name "*.vo" -o -name "*.vok" -o -name "*.vos" \
          -o -name "*.glob" -o -name "*.aux" -o -name ".*.aux" \
          -o -name ".lia.cache" \) -type f -delete 2>/dev/null || true
rm -f Makefile.coq Makefile.coq.conf .coqdeps.d 2>/dev/null || true
info "Clean complete."
echo ""

# Step 2: Verify directory structure
info "Verifying directory structure..."
if [[ ! -d "LTL" ]] || [[ ! -d "MUDA" ]] || [[ ! -d "Fairness" ]]; then
    error "Missing required directories. Expected: LTL/, MUDA/, Fairness/"
fi

# Count .v files
LTL_COUNT=$(find LTL -name "*.v" 2>/dev/null | wc -l | tr -d ' ')
MUDA_COUNT=$(find MUDA -name "*.v" 2>/dev/null | wc -l | tr -d ' ')
FAIRNESS_COUNT=$(find Fairness -name "*.v" 2>/dev/null | wc -l | tr -d ' ')

info "Found $LTL_COUNT LTL files, $MUDA_COUNT MUDA files, $FAIRNESS_COUNT Fairness files"
echo ""

# Step 3: Generate _CoqProject
info "Generating _CoqProject..."
cat > _CoqProject <<'EOF'
# Coq Project Configuration for MUDA Fairness Verification
# Generated by build.sh

# Logical roots
-R LTL MUDA.LTL
-R MUDA MUDA.MUDA
-R Fairness MUDA.Fairness

# Suppress common warnings
-arg -w -arg -notation-overridden
-arg -w -arg -redundant-canonical-projection

# ===== LTL Foundation (Layer 1) =====
LTL/Syntax.v
LTL/Semantics.v
LTL/Soundness.v
LTL/Completeness.v
LTL/LTL.v

# ===== MUDA Protocol (Layer 2) =====
MUDA/Types.v
MUDA/State.v
MUDA/Sorting.v
MUDA/Matching.v
MUDA/ClearingPrice.v
MUDA/Transitions.v
MUDA/MUDA.v

# ===== Fairness Verification (Layer 3) =====
Fairness/QuantityFairness.v
Fairness/PriorityFairness.v
Fairness/Finality.v
Fairness/Maximality.v
Fairness/RejectionFairness.v
Fairness/All.v
EOF

info "_CoqProject generated."
echo ""

# Step 4: Check if files in _CoqProject exist
info "Verifying all files exist..."
MISSING=0
while IFS= read -r line; do
    # Skip comments and flags
    [[ "$line" =~ ^# ]] && continue
    [[ "$line" =~ ^-.*$ ]] && continue
    [[ -z "$line" ]] && continue
    
    if [[ ! -f "$line" ]]; then
        warn "Missing file: $line"
        MISSING=$((MISSING + 1))
    fi
done < _CoqProject

if [[ $MISSING -gt 0 ]]; then
    error "Found $MISSING missing files. Please create them before building."
fi
info "All files verified."
echo ""

# Step 5: Generate Makefile from _CoqProject
info "Generating Makefile.coq..."
coq_makefile -f _CoqProject -o Makefile.coq || error "coq_makefile failed"
info "Makefile.coq generated."
echo ""

# Step 6: Determine number of parallel jobs
NPROC=2
if command -v nproc &> /dev/null; then
    NPROC=$(nproc)
elif command -v sysctl &> /dev/null; then
    NPROC=$(sysctl -n hw.ncpu 2>/dev/null || echo 2)
elif command -v getconf &> /dev/null; then
    NPROC=$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)
fi

info "Building with $NPROC parallel jobs..."
echo ""

# Step 7: Build with timing
START_TIME=$(date +%s)
if make -f Makefile.coq -j"$NPROC"; then
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    echo ""
    info "✓ Build successful in ${DURATION}s"
else
    echo ""
    error "Build failed. Check errors above."
fi

# Step 8: Check for admitted lemmas
echo ""
info "Checking for admitted lemmas..."
ADMITS=$(grep -r "Admitted\." LTL/ MUDA/ Fairness/ 2>/dev/null | wc -l | tr -d ' ')
if [[ $ADMITS -eq 0 ]]; then
    info "✓ No admitted lemmas found. All proofs complete!"
else
    warn "Found $ADMITS admitted lemma(s):"
    grep -rn "Admitted\." LTL/ MUDA/ Fairness/ 2>/dev/null || true
fi

echo ""
echo "================================================"
echo "  Build Complete"
echo "================================================"
echo ""
info "Next steps:"
info "  - Run './check.sh' to verify proofs"
info "  - Run 'make -f Makefile.coq html' to generate docs"
echo ""